import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./Components/layouts/Header";
import { Footer } from "./Components/layouts/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <p className="w-full bg-anounceTag text-white text-center">
          {"Announcement placeholder"}
        </p>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
